In [ ]:
!pip install chromadb

Collecting chromadb
  Downloading chromadb-1.0.7-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.9 kB)
Collecting build>=1.0.3 (from chromadb)
  Downloading build-1.2.2.post1-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: pydantic>=1.9 in /usr/local/lib/python3.11/dist-packages (from chromadb) (2.11.3)
Collecting chroma-hnswlib==0.7.6 (from chromadb)
  Downloading chroma_hnswlib-0.7.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (252 bytes)
Collecting fastapi==0.115.9 (from chromadb)
  Downloading fastapi-0.115.9-py3-none-any.whl.metadata (27 kB)
Collecting uvicorn>=0.18.3 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading uvicorn-0.34.2-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: numpy>=1.22.5 in /usr/local/lib/python3.11/dist-packages (from chromadb) (2.0.2)
Collecting posthog>=2.4.0 (from chromadb)
  Downloading posthog-4.0.1-py2.py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (4.13.2)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.21.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.5 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (1.32.1)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.32.1-py3-none-any.whl.metadata (2.5 kB)
Collecting opentelemetry-instrumentation-fastapi>=0.41b0 (from chromadb)
  Downloading opentelemetry_instrumentation_fastapi-0.53b1-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (1.32.1)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from chromadb) (0.21.1)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading PyPika-0.48.9.tar.gz (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 3.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (4.67.1)
Collecting overrides>=7.3.1 (from chromadb)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.11/dist-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (1.71.0)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-4.3.0-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (10 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (0.15.2)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-32.0.1-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.11/dist-packages (from chromadb) (9.1.2)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (6.0.2)
Collecting mmh3>=4.0.1 (from chromadb)
  Downloading mmh3-5.1.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (16 kB)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.11/dist-packages (from chromadb) (3.10.16)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (4.23.0)
Collecting starlette<0.46.0,>=0.40.0 (from fastapi==0.115.9->chromadb)
  Downloading starlette-0.45.3-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging>=19.1 in /usr/local/lib/python3.11/dist-packages (from build>=1.0.3->chromadb) (24.2)
Collecting pyproject_hooks (from build>=1.0.3->chromadb)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->chromadb) (4.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->chromadb) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->chromadb) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=4.19.0->chromadb) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=4.19.0->chromadb) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=4.19.0->chromadb) (0.24.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: google-auth>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.38.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.3)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: oauthlib>=3.2.2 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (3.2.2)
Requirement already satisfied: urllib3>=1.24.2 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.4.0)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb)
  Downloading durationpy-0.9-py3-none-any.whl.metadata (338 bytes)
Collecting coloredlogs (from onnxruntime>=1.14.1->chromadb)
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.11/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.2.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.4)
Requirement already satisfied: sympy in /usr/local/lib/python3.11/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.13.1)
Requirement already satisfied: deprecated>=1.2.6 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (1.2.18)
Requirement already satisfied: importlib-metadata<8.7.0,>=6.0 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (8.6.1)
Requirement already satisfied: googleapis-common-protos~=1.52 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.70.0)
Collecting opentelemetry-exporter-otlp-proto-common==1.32.1 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.32.1-py3-none-any.whl.metadata (1.9 kB)
Collecting opentelemetry-proto==1.32.1 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.32.1-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-instrumentation-asgi==0.53b1 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_instrumentation_asgi-0.53b1-py3-none-any.whl.metadata (2.1 kB)
Collecting opentelemetry-instrumentation==0.53b1 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_instrumentation-0.53b1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: opentelemetry-semantic-conventions==0.53b1 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb) (0.53b1)
Collecting opentelemetry-util-http==0.53b1 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_util_http-0.53b1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-instrumentation==0.53b1->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb) (1.17.2)
Collecting asgiref~=3.0 (from opentelemetry-instrumentation-asgi==0.53b1->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading asgiref-3.8.1-py3-none-any.whl.metadata (9.3 kB)
Collecting backoff>=1.10.0 (from posthog>=2.4.0->chromadb)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: distro>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from posthog>=2.4.0->chromadb) (1.9.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=1.9->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic>=1.9->chromadb) (2.33.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=1.9->chromadb) (0.4.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->chromadb) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->chromadb) (2.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.11/dist-packages (from tokenizers>=0.13.2->chromadb) (0.30.2)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer>=0.9.0->chromadb) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Collecting httptools>=0.6.3 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading httptools-0.6.4-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.6 kB)
Collecting python-dotenv>=0.13 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading python_dotenv-1.1.0-py3-none-any.whl.metadata (24 kB)
Collecting uvloop!=0.15.0,!=0.15.1,>=0.14.0 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading uvloop-0.21.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Collecting watchfiles>=0.13 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading watchfiles-1.0.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.11/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (4.9.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2025.3.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata<8.7.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.1)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx>=0.27.0->chromadb) (1.3.1)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime>=1.14.1->chromadb)
  Downloading humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.6.1)
Downloading chromadb-1.0.7-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 70.0 MB/s eta 0:00:00
Downloading chroma_hnswlib-0.7.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 57.2 MB/s eta 0:00:00
Downloading fastapi-0.115.9-py3-none-any.whl (94 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.9/94.9 kB 6.1 MB/s eta 0:00:00
Downloading bcrypt-4.3.0-cp39-abi3-manylinux_2_34_x86_64.whl (284 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.2/284.2 kB 19.9 MB/s eta 0:00:00
Downloading build-1.2.2.post1-py3-none-any.whl (22 kB)
Downloading kubernetes-32.0.1-py2.py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 57.1 MB/s eta 0:00:00
Downloading mmh3-5.1.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (101 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.6/101.6 kB 7.3 MB/s eta 0:00:00
Downloading onnxruntime-1.21.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 73.9 MB/s eta 0:00:00
Downloading opentelemetry_exporter_otlp_proto_grpc-1.32.1-py3-none-any.whl (18 kB)
Downloading opentelemetry_exporter_otlp_proto_common-1.32.1-py3-none-any.whl (18 kB)
Downloading opentelemetry_proto-1.32.1-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.9/55.9 kB 3.9 MB/s eta 0:00:00
Downloading opentelemetry_instrumentation_fastapi-0.53b1-py3-none-any.whl (12 kB)
Downloading opentelemetry_instrumentation-0.53b1-py3-none-any.whl (30 kB)
Downloading opentelemetry_instrumentation_asgi-0.53b1-py3-none-any.whl (16 kB)
Downloading opentelemetry_util_http-0.53b1-py3-none-any.whl (7.3 kB)
Downloading overrides-7.7.0-py3-none-any.whl (17 kB)
Downloading posthog-4.0.1-py2.py3-none-any.whl (92 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.0/92.0 kB 5.9 MB/s eta 0:00:00
Downloading uvicorn-0.34.2-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.5/62.5 kB 4.6 MB/s eta 0:00:00
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading durationpy-0.9-py3-none-any.whl (3.5 kB)
Downloading httptools-0.6.4-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (459 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 459.8/459.8 kB 29.0 MB/s eta 0:00:00
Downloading python_dotenv-1.1.0-py3-none-any.whl (20 kB)
Downloading starlette-0.45.3-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.5/71.5 kB 5.9 MB/s eta 0:00:00
Downloading uvloop-0.21.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 104.2 MB/s eta 0:00:00
Downloading watchfiles-1.0.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (454 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 454.8/454.8 kB 22.3 MB/s eta 0:00:00
Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 4.2 MB/s eta 0:00:00
Downloading pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Downloading asgiref-3.8.1-py3-none-any.whl (23 kB)
Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 8.1 MB/s eta 0:00:00
Building wheels for collected packages: pypika
  Building wheel for pypika (pyproject.toml) ... done
  Created wheel for pypika: filename=pypika-0.48.9-py2.py3-none-any.whl size=53800 sha256=c219bb2d6b8460c21c91f72c0b30c2c0da28e43b4bdffdb209ac84c748ccffe9
  Stored in directory: /root/.cache/pip/wheels/a3/01/bd/4c40ceb9d5354160cb186dcc153360f4ab7eb23e2b24daf96d
Successfully built pypika
Installing collected packages: pypika, durationpy, uvloop, uvicorn, python-dotenv, pyproject_hooks, overrides, opentelemetry-util-http, opentelemetry-proto, mmh3, humanfriendly, httptools, chroma-hnswlib, bcrypt, backoff, asgiref, watchfiles, starlette, posthog, opentelemetry-exporter-otlp-proto-common, coloredlogs, build, onnxruntime, kubernetes, fastapi, opentelemetry-instrumentation, opentelemetry-instrumentation-asgi, opentelemetry-exporter-otlp-proto-grpc, opentelemetry-instrumentation-fastapi, chromadb
Successfully installed asgiref-3.8.1 backoff-2.2.1 bcrypt-4.3.0 build-1.2.2.post1 chroma-hnswlib-0.7.6 chromadb-1.0.7 coloredlogs-15.0.1 durationpy-0.9 fastapi-0.115.9 httptools-0.6.4 humanfriendly-10.0 kubernetes-32.0.1 mmh3-5.1.0 onnxruntime-1.21.1 opentelemetry-exporter-otlp-proto-common-1.32.1 opentelemetry-exporter-otlp-proto-grpc-1.32.1 opentelemetry-instrumentation-0.53b1 opentelemetry-instrumentation-asgi-0.53b1 opentelemetry-instrumentation-fastapi-0.53b1 opentelemetry-proto-1.32.1 opentelemetry-util-http-0.53b1 overrides-7.7.0 posthog-4.0.1 pypika-0.48.9 pyproject_hooks-1.2.0 python-dotenv-1.1.0 starlette-0.45.3 uvicorn-0.34.2 uvloop-0.21.0 watchfiles-1.0.5

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Read CSV

In [ ]:
df_external = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/CompassDigital/data/Data_External.csv')
df_internal = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/CompassDigital/data/Data_Internal.csv')

In [ ]:
df_external.head()

                                PRODUCT_NAME  UNIT_OF_MEASURE
0                  5 HOUR XTRA GRAPE 1.93 OZ                1
1                     B - PB & HONEY SAMMICH                1
2  B - RUDY FARMS - SAUSAGE AND BISCUIT TWIN                1
3                            BANANAS - FRESH                1
4                    BOBOS PB&J GRAPE 2.1 OZ                1

In [ ]:
df_internal.head()

,NAME,OCS_NAME,LONG_NAME
0,3 Mskt DkChocMnt 1.24oz,3 Mskt DkChocMnt 1.24oz,3 Musketeers Dark Chocolate Mint (1.24oz)
1,NaN,Costco Choc Mini 4.69lb,Costco Chocolate Mini (4.69lb)
2,Dove Dk Choc Bars 1.3oz,Dove Dk Choc Bars 1.3oz,Dove Dark Chocolate Bars (1.3oz)
3,Fishers ChocPnut 3.5oz,Fishers ChocPnut 3.5oz,Fisher's Chocolate Peanuts (3.5oz)
4,HariboGummiGoldBear2oz,HariboGummiGoldBear2oz,Haribo Gummi Gold-Bears (2oz)

In [ ]:
df_internal.shape, df_external.shape

((16192, 3), (43, 2))

### IDEA
- Using External Data, create a vector store
- Using LLM - providing the (1) NAME, (2) OCS_NAME and (3) LONG_NAME, ask for the matched PRODUCT_NAME
- Note: if there is no best match, return NULL

In [ ]:
from sentence_transformers import SentenceTransformer
import chromadb

In [ ]:
embedding_model_name = 'sentence-transformers/all-MiniLM-L6-v2'
embedding_model = SentenceTransformer(embedding_model_name)
embedding_model.to('cuda')

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False}) with Transformer model: BertModel
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

### Create ChromaDB (Vector Store)
- Collection Name: product_name
- Distance Measure: Cosine Similarity, [0, 1]
    - the smaller the value, the more the similarity

In [ ]:
chroma_client = chromadb.Client()

collection = chroma_client.create_collection(
    name='product_name',
    metadata={'hnsw:space': 'cosine'}
)

### Prepare List of Product Data
- For each product in external dataframe
  - merge NAME, OCS_NAME and LONG_NAME as a single row (ignore NA)

In [ ]:
lst_product_data = []
for idx, row in df_internal.iterrows():
    row = row.fillna('')
    product = ';'.join([e for e in [row.NAME, row.OCS_NAME, row.LONG_NAME] if e != ''])
    lst_product_data.append(product)

#### Create Embeddings

In [ ]:
embeddings = []
batch_size = 32

for i in range(0, len(lst_product_data),batch_size):
    if i%100 ==0: print(i)
    batch = lst_product_data[i:i+batch_size]
    batch_embeddings = embedding_model.encode(
        batch,
        convert_to_tensor=True,
        show_progress_bar=False
    )
    embeddings.extend(batch_embeddings.cpu().numpy().tolist())

0
800
1600
2400
3200
4000
4800
5600
6400
7200
8000
8800
9600
10400
11200
12000
12800
13600
14400
15200
16000

#### Store in ChromaDB

- ids - use to reference the internal dataframe index id
- meta - using LONG_NAME as well, ease for getting the result

In [ ]:
lst_meta = []

for n in df_internal.LONG_NAME.tolist():
    d = {'LONG_NAME': n}
    lst_meta.append(d)

In [ ]:
# store in chromaDB
for i in range(0, len(lst_product_data),batch_size):
    embeddings_batch = embeddings[i:i+batch_size]
    lst_product_data_batch = lst_product_data[i:i+batch_size]
    ids = [f'{j}' for j in range(i, i+batch_size)]
    lst_meta_batch = lst_meta[i:i+batch_size]
    collection.add(
        embeddings=embeddings_batch,
        documents=lst_product_data_batch,
        ids=ids,
        metadatas=lst_meta_batch
    )

### Search Best Product Name
- if the cosine distance >= 0.3, return None

In [ ]:
lst_match_result = []

for idx, row in df_external.iterrows():
    query_embedding = embedding_model.encode(
        row.PRODUCT_NAME,
        convert_to_tensor=True,
        show_progression_bar=False
    ).cpu().numpy().tolist()

    # query chromadb
    result = collection.query(
        query_embeddings=[query_embedding],
        n_results = 1
    )
    distance = result['distances'][0][0]
    dataframe_idx = int(result['ids'][0][0])

    if distance < 0.3: #
        #match_name = df_internal.iloc[dataframe_idx].LONG_NAME # referening ids
        match_name = result['metadatas'][0][0]['LONG_NAME']
        lst_match_result.append(match_name)
    else:# cannot find
        lst_match_result.append(None)

In [ ]:
df_result = df_external.copy()
df_result['internal_product_name'] = lst_match_result

In [ ]:
display(df_result)

,PRODUCT_NAME,UNIT_OF_MEASURE,internal_product_name
0,5 HOUR XTRA GRAPE 1.93 OZ,1,5 Hour Energy Grape (1.93oz)
1,B - PB & HONEY SAMMICH,1,None
2,B - RUDY FARMS - SAUSAGE AND BISCUIT TWIN,1,Rudys Farm Cheese & Sausage Biscuit Twin #1208...
3,BANANAS - FRESH,1,None
4,BOBOS PB&J GRAPE 2.1 OZ,1,None
5,BODY ARMOR STRWBRY BANANA 16 OZ,1,None
6,BR ESPRESSO W/ CREAM 11 OZ,1,None
7,Bumble Bee Tuna Salad 3.5oz,1,Bumble Bee Tuna Salad with Crackers (3.5oz)
8,CELSIUS ORANGE ENERGY 12 OZ,1,None
9,CELSIUS PEACH VIBE 12 OZ,1,Celsius Sparkling Peach Vibe (12oz)
10,DIET MOUNTAIN DEW 20 OZ,1,None
11,DOLE STRWBRY LEMONADE 20 OZ,1,None
12,DOVE BAR DARK CHOC 1.44 OZ,1,Dove Dark Chocolate Bar (1.44oz)
13,Dr Pepper 12oz Can,1,None
14,F - TURKEY HAM CHS HM WRAP,1,None
15,F- WHITE CASTLE BREAKFAST SANDWICH,1,None
16,FAIRLIFE 2% STRAWBERRY MILK 14 OZ,1,Fairlife 2% Ultra Filtered Strawberry Milk (14oz)
17,FL Doritos Spicy Sweet Chili LSS 1.75oz Bag,1,None
18,GRANDMA'S MINI VN 3.7 OZ,1,None
19,Haribo Gold-Bears Gummi Candy 4oz.,1,Haribo Gummi Gold-Bears (.4oz)
20,HY Hersheys Milk Chocolate w Almonds 1.45oz Each,1,Hersheys Milk Chocolate wtih Almonds (2.25oz)
21,KF - NY MIXED BERRY CHSCAKE CUP,1,None
22,Kraft Mac & Cheese Original Cups 2.05 oz.,1,Kraft Macaroni & Cheese Original (2.05oz)
23,LSS-BRIM'S BBQ PORK RINDS,1,Brim's Sweet & Mild BBQ Pork Rinds (.875oz)
24,LSS-CRUNCHY CHEETO,1,None
25,LSS-DORITOS COOL RANCH,1,None
26,LSS-FLAMIN HOT CHEETOS,1,None
27,LSS-RUFFLES CHDR & SOUR CREAM,1,None
28,M&M PLAIN,1,None
29,MF-BOSTON CREME HONEY BUN,1,Mrs. Freshleys Boston Creme Honey Bun (5oz)
30,MF-CHOCOLATE MINI DONUTS,1,Euro Classic Mini Chocolate French Beignet Don...
31,MINUTE MAID FRUIT PUNCH 20 OZ,1,None
32,MOUNTAIN DEW ZERO 20 OZ,1,None
33,ORANGE FANTA 20 OZ,1,Fanta Peach (20oz)
34,Pillsbury Mini SOFT BAKED Chocolate Chip Cooki...,1,Pillsbury Mini Snickerdoodle Cookies (3oz)
35,Pillsbury Soft Baked Confetti Cookies 3oz,1,Pillsbury Mini Soft Baked Confetti Cookies (3oz)
36,POP CHIP BBQ .8 OZ,1,Popchips BBQ (3.5oz)
37,SKITTLES ORIG GUMMIES 5.8 OZ,1,Sutlers 12 Flavor Gummy Bears (6oz)
38,STARBUCKS DOUBLESHOT + ENG-VAN 15 OZ,1,Starbucks DoubleShot Energy Caramel (15oz)
39,STONIES PEPR/CHS/JAL .98 OZ,1,None
40,Sweet Serenity Choc Chip 3 oz,1,None
41,SWEET SERENITY CHOC CHIP COOKIES 3 OZ,1,Appleton Triple Chip Chocolate Cookie (3.5oz)
42,YOO HOO CHOC. 11 OZ CANS,1,Yoo-hoo Chocolate Drink Can (11oz)

In [ ]:
df_result.to_csv('/content/drive/MyDrive/Colab Notebooks/CompassDigital/data/result.csv', index=False)

### Prompt Approach

In [ ]:
def search_product_name(prompt, threshold=0.3):

    prompt_embedding = embedding_model.encode(prompt).tolist()

    query_kwargs = {
        "query_embeddings": [prompt_embedding],
        "n_results": 1,
    }

    results = collection.query(**query_kwargs)

    # Parse results
    dist, dataframe_idx = results["distances"][0][0], int(results["ids"][0][0])
    if dist < threshold:
        match_product_name = df_internal.iloc[dataframe_idx].LONG_NAME
        return match_product_name
    else:
        return None

In [ ]:
def build_standard_prompt(product_name):
    base_prompt = f"""
                    Find product matching: '{product_name}'
                    """
    return base_prompt.strip()


# example
prompt = build_standard_prompt('5 Hour Energy Grape (1.93oz)')
search_product_name(prompt)

'5 Hour Energy Grape (1.93oz)'

In [ ]:
lst_result = []
for idx, row in df_external.iterrows():
    prompt = build_standard_prompt(row['PRODUCT_NAME'])
    result = search_product_name(prompt)
    print(prompt, '; Match:', result )
    lst_result.append(result)

Find product matching: '5 HOUR XTRA GRAPE 1.93 OZ' ; Match: None
Find product matching: 'B - PB & HONEY SAMMICH' ; Match: None
Find product matching: 'B - RUDY FARMS - SAUSAGE AND BISCUIT TWIN' ; Match: None
Find product matching: 'BANANAS - FRESH' ; Match: None
Find product matching: 'BOBOS PB&J GRAPE 2.1 OZ' ; Match: None
Find product matching: 'BODY ARMOR STRWBRY BANANA 16 OZ' ; Match: None
Find product matching: 'BR ESPRESSO W/ CREAM 11 OZ' ; Match: None
Find product matching: 'Bumble Bee Tuna Salad 3.5oz' ; Match: Bumble Bee Tuna Salad with Crackers (3.5oz)
Find product matching: 'CELSIUS ORANGE ENERGY 12 OZ' ; Match: None
Find product matching: 'CELSIUS PEACH VIBE 12 OZ' ; Match: Celsius Sparkling Peach Vibe (12oz)
Find product matching: 'DIET MOUNTAIN DEW 20 OZ' ; Match: None
Find product matching: 'DOLE STRWBRY LEMONADE 20 OZ' ; Match: None
Find product matching: 'DOVE BAR DARK CHOC 1.44 OZ' ; Match: Dove Milk Chocolate Bar (1.3oz)
Find product matching: 'Dr Pepper 12oz Can' ; Match: None
Find product matching: 'F - TURKEY HAM CHS HM WRAP' ; Match: None
Find product matching: 'F- WHITE CASTLE BREAKFAST SANDWICH' ; Match: None
Find product matching: 'FAIRLIFE 2% STRAWBERRY MILK 14 OZ' ; Match: Fairlife 2% Ultra Filtered Strawberry Milk (14oz)
Find product matching: 'FL Doritos Spicy Sweet Chili LSS 1.75oz Bag' ; Match: None
Find product matching: 'GRANDMA'S MINI VN 3.7 OZ' ; Match: None
Find product matching: 'Haribo Gold-Bears Gummi Candy 4oz.' ; Match: Haribo Gummi Gold-Bears (.4oz)
Find product matching: 'HY Hersheys Milk Chocolate w Almonds 1.45oz Each' ; Match: Hersheys Milk Chocolate wtih Almonds (2.25oz)
Find product matching: 'KF - NY MIXED BERRY CHSCAKE CUP' ; Match: None
Find product matching: 'Kraft Mac & Cheese Original Cups 2.05 oz.' ; Match: Kraft Macaroni & Cheese Original (2.05oz)
Find product matching: 'LSS-BRIM'S BBQ PORK RINDS' ; Match: None
Find product matching: 'LSS-CRUNCHY CHEETO' ; Match: None
Find product matching: 'LSS-DORITOS COOL RANCH' ; Match: None
Find product matching: 'LSS-FLAMIN HOT CHEETOS' ; Match: None
Find product matching: 'LSS-RUFFLES CHDR & SOUR CREAM' ; Match: None
Find product matching: 'M&M PLAIN' ; Match: None
Find product matching: 'MF-BOSTON CREME HONEY BUN' ; Match: None
Find product matching: 'MF-CHOCOLATE MINI DONUTS' ; Match: None
Find product matching: 'MINUTE MAID FRUIT PUNCH 20 OZ' ; Match: None
Find product matching: 'MOUNTAIN DEW ZERO 20 OZ' ; Match: None
Find product matching: 'ORANGE FANTA 20 OZ' ; Match: None
Find product matching: 'Pillsbury Mini SOFT BAKED Chocolate Chip Cookies Bag 3oz' ; Match: Pillsbury Mini Snickerdoodle Cookies (3oz)
Find product matching: 'Pillsbury Soft Baked Confetti Cookies 3oz' ; Match: Pillsbury Mini Soft Baked Confetti Cookies (3oz)
Find product matching: 'POP CHIP BBQ .8 OZ' ; Match: None
Find product matching: 'SKITTLES ORIG GUMMIES 5.8 OZ' ; Match: None
Find product matching: 'STARBUCKS DOUBLESHOT + ENG-VAN 15 OZ' ; Match: None
Find product matching: 'STONIES PEPR/CHS/JAL .98 OZ' ; Match: None
Find product matching: 'Sweet Serenity Choc Chip 3 oz' ; Match: None
Find product matching: 'SWEET SERENITY CHOC CHIP COOKIES 3 OZ' ; Match: None
Find product matching: 'YOO HOO CHOC. 11 OZ CANS' ; Match: None

In [ ]:
df_result_from_prompt = df_external.copy()
df_result_from_prompt['internal'] = lst_result

In [ ]:
df_result_from_prompt

,PRODUCT_NAME,UNIT_OF_MEASURE,internal
0,5 HOUR XTRA GRAPE 1.93 OZ,1,None
1,B - PB & HONEY SAMMICH,1,None
2,B - RUDY FARMS - SAUSAGE AND BISCUIT TWIN,1,None
3,BANANAS - FRESH,1,None
4,BOBOS PB&J GRAPE 2.1 OZ,1,None
5,BODY ARMOR STRWBRY BANANA 16 OZ,1,None
6,BR ESPRESSO W/ CREAM 11 OZ,1,None
7,Bumble Bee Tuna Salad 3.5oz,1,Bumble Bee Tuna Salad with Crackers (3.5oz)
8,CELSIUS ORANGE ENERGY 12 OZ,1,None
9,CELSIUS PEACH VIBE 12 OZ,1,Celsius Sparkling Peach Vibe (12oz)
10,DIET MOUNTAIN DEW 20 OZ,1,None
11,DOLE STRWBRY LEMONADE 20 OZ,1,None
12,DOVE BAR DARK CHOC 1.44 OZ,1,Dove Milk Chocolate Bar (1.3oz)
13,Dr Pepper 12oz Can,1,None
14,F - TURKEY HAM CHS HM WRAP,1,None
15,F- WHITE CASTLE BREAKFAST SANDWICH,1,None
16,FAIRLIFE 2% STRAWBERRY MILK 14 OZ,1,Fairlife 2% Ultra Filtered Strawberry Milk (14oz)
17,FL Doritos Spicy Sweet Chili LSS 1.75oz Bag,1,None
18,GRANDMA'S MINI VN 3.7 OZ,1,None
19,Haribo Gold-Bears Gummi Candy 4oz.,1,Haribo Gummi Gold-Bears (.4oz)
20,HY Hersheys Milk Chocolate w Almonds 1.45oz Each,1,Hersheys Milk Chocolate wtih Almonds (2.25oz)
21,KF - NY MIXED BERRY CHSCAKE CUP,1,None
22,Kraft Mac & Cheese Original Cups 2.05 oz.,1,Kraft Macaroni & Cheese Original (2.05oz)
23,LSS-BRIM'S BBQ PORK RINDS,1,None
24,LSS-CRUNCHY CHEETO,1,None
25,LSS-DORITOS COOL RANCH,1,None
26,LSS-FLAMIN HOT CHEETOS,1,None
27,LSS-RUFFLES CHDR & SOUR CREAM,1,None
28,M&M PLAIN,1,None
29,MF-BOSTON CREME HONEY BUN,1,None
30,MF-CHOCOLATE MINI DONUTS,1,None
31,MINUTE MAID FRUIT PUNCH 20 OZ,1,None
32,MOUNTAIN DEW ZERO 20 OZ,1,None
33,ORANGE FANTA 20 OZ,1,None
34,Pillsbury Mini SOFT BAKED Chocolate Chip Cooki...,1,Pillsbury Mini Snickerdoodle Cookies (3oz)
35,Pillsbury Soft Baked Confetti Cookies 3oz,1,Pillsbury Mini Soft Baked Confetti Cookies (3oz)
36,POP CHIP BBQ .8 OZ,1,None
37,SKITTLES ORIG GUMMIES 5.8 OZ,1,None
38,STARBUCKS DOUBLESHOT + ENG-VAN 15 OZ,1,None
39,STONIES PEPR/CHS/JAL .98 OZ,1,None
40,Sweet Serenity Choc Chip 3 oz,1,None
41,SWEET SERENITY CHOC CHIP COOKIES 3 OZ,1,None
42,YOO HOO CHOC. 11 OZ CANS,1,None